# Generated by Django 4.0.5 on 2022-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='game',
            field=models.CharField(max_length=5),
        ),
    ]
