# Generated by Django 4.0.5 on 2022-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='game',
            field=models.CharField(choices=[('pc', 'pc'), ('gpc', 'gpc'), ('vr', 'vr'), ('xbox', 'xbox'), ('ps', 'ps')], default='ps', max_length=5),
        ),
    ]
